name: blob_counter
channels:
  - anaconda
  - conda-forge
dependencies:
  - scikit-image=0.19.3=py310h769672d_2
  - matplotlib-base=3.7.1=py310h1128e8f_1
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - tifffile=2023.2.28=pyhd8ed1ab_0
